CHANGELOG.md
fields/default/examples/empty.json
fields/default/examples/full.json
fields/default/fields_list.json

Field with path accidents.has_accidents
Field with path fines.has_fines
Добавлены новые статусные поля `has_accidents`  `has_fines`
Исправление #22  (issue)
>
> * Добавь заголовок новой версии вида `## v1.x.x`, если его не существует
> * Добавь описания в секции `added`/`changed`/`fixed`
> * Добавь ссылку на соответствующие issues `[#000]`
> * Добавь ссылки на issues в конец документа

Added new fields

---

.codecov.yml
.editorconfig
.gitattributes
.github/stale.yml
.scrutinizer.yml
.travis.yml
CHANGELOG.md
README.md
composer.json
sdk/php/src/Specifications.php
sdk/php/src/Structures/AbstractStructure.php
sdk/php/src/Structures/Field.php
sdk/php/src/Structures/IdentifierType.php
sdk/php/src/Structures/Source.php
sdk/php/src/Structures/VehicleMark.php
sdk/php/src/Structures/VehicleModel.php
sdk/php/tests/AbstractTestCase.php
sdk/php/tests/SpecificationsTest.php

- Migrate to the [Travis CI][travis-ci]
- **PHP SDK** minimal PHP version now is 7.0 _([version 5.6 is not supported since 31 Dec 2018][php-supported-versions])_
- **PHP SDK** code a little bit refactored for PHP version 7.0
- **PHP SDK** Static code analyzer `phpstan` installed as `dev` dependency
[php-supported-versions]:http://php.net/supported-versions.php
[travis-ci]:https://travis-ci.org/avtocod/specs

Travis config added

---

CHANGELOG.md
fields/default/fields_list.json
sdk/php/src/Specifications.php
sdk/php/src/Structures/Field.php
sdk/php/tests/SpecificationsTest.php
sdk/php/tests/Structures/FieldTest.php
sources/default/sources_list.json

Это новый функционал? | Да 
- Add `fillable_by` field for fields specification. This version includes sources that we could find out with responces stubs. **May be incompleted**.
- Add 'references.base' source into specification
- Add 'tech.base' source into specification
- Add 'pledge.house' source into specification
- Add 'av.taxi' source into specification
- Add 'taxi.registry' source into specificatio
Исправление #34
(https://github.com/avtocod/specs/blob/master/CHANGELOG.md)

Add fillable_by field for field's spec

---

.editorconfig
.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CHANGELOG.md
composer.json
sdk/php/phpunit.xml.dist
sdk/php/src/Specifications.php
sdk/php/tests/AbstractTestCase.php
sdk/php/tests/SpecificationsDatum/SpecFilesTest.php
sdk/php/tests/SpecificationsTest.php
sdk/php/tests/Structures/AbstractStructureTestCase.php
sdk/php/tests/Structures/FieldTest.php
sdk/php/tests/Structures/IdentifierTypeTest.php
sdk/php/tests/Structures/SourceTest.php
sdk/php/tests/Structures/VehicleMarkTest.php
sdk/php/tests/Structures/VehicleModelTest.php
sdk/php/tests/Structures/VehicleTypeTest.php
sdk/php/tests/bootstrap.php

Это новый функционал? | Нет
- **PHP SDK** minimal `PHP` version now is `7.1.3`
- **PHP SDK** maximal `illuminate/support` dependency version now is `5.8.x`
- **PHP SDK** type-hinting in tests updated

Up PHP and illuminate/* versions

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

Added source `dtp.registry`.
This fileds are fiilable now by `dtp.registry`:
- `accidents.history.items[].number`
- `accidents.history.items[].accident.date`
- `accidents.history.items[].type`
- `accidents.history.items[].state`
- `accidents.history.items[].vehicle.brand.name`
- `accidents.history.items[].vehicle.model.name`
- `accidents.history.items[].vehicle.year`
- `accidents.history.items[].geo`
- `accidents.history.items[].damage.points`
- `accidents.history.items[].damage.codes`
- `accidents.history.items[].actuality.date`
Closes #105

Added source "dtp.registry"

---

CHANGELOG.md
fields/default/fields_list.json
sdk/php/tests/SpecificationsTest.php

- `SpecificationsTest::testFieldsListAndReportSchemaAreSame` improved [#111]
- Field with path `identifiers.vehicle.body` also fallible by `gibdd.history` source in `./fields/default/fields_list.json` [#111]
[#111]:https://github.com/avtocod/specs/issues/111
Closes #111

Add check that all report fillable_by source are exist in field

---

CHANGELOG.md
reports/default/examples/full.json
reports/default/json-schema.json

Исправлено ключевое слово с `oneOf` на `anyOf` в полях спецификации отчёта `pledges.items[].pledgors[].name`, `pledges.items[].pledgees[].name`

Fixed oneOf keyword on anyOf

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `ownership.history.items[].date.start` also fillable by `base`, `base.ext`
- Field with path `ownership.history.items[].date.end` also fillable by `base`, `base.ext`
- Field with path `ownership.history.items[].owner.type` also fillable by `base`, `base.ext`
- Field with path `ownership.history.items[].last_operation.code` also fillable by `base`, `base.ext`, `base.alt`
- Field with path `ownership.history.items[].last_operation.description` also fillable by `base`, `base.ext`, `base.alt`

Added sources to owneship fields fillable by

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `accidents.history.items[].damage.raw` also fillable by `gibdd.dtp`
- Field with path `accidents.history.items[].damage.raw` is not fillable by `base.moscow` source now

Fix accidents.history.items[].damage.raw field

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Extend enum with `UNKNOWN` value for field `insurance.osago.items[].insurant.type` in `./reports/default/json-schema.json`
- Extend enum with `UNKNOWN` value for field `insurance.osago.items[].owner.type` in `./reports/default/json-schema.json`

Extend enum with 'UNKNOWN' value for some fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `insurance.osago.items[].owner.tin` also fillable by `osago.registry`
- Field with path `insurance.osago.items[].number` also fillable by `osago.registry`

Draft: add fillable by for osago.registry fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Description for a field with path `accidents.insurance.date.update` in `./fields/default/fields_list.json`
- Description for a field with path `accidents.insurance.items[].date.event` in `./fields/default/fields_list.json`
- Description for a field with path `accidents.insurance.items[].insurer.name` in `./fields/default/fields_list.json`
- Description for a field with path `accidents.insurance.items[].policy.series` in `./fields/default/fields_list.json`
- Description for a field with path `accidents.insurance.items[].policy.number` in `./fields/default/fields_list.json`
- Description for a field with path `accidents.insurance.items[].actuality.date` in `./fields/default/fields_list.json`

Drafr: Rename accidents.insurance fields description

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `fines.items[].vendor.type` also fillable by `fines.base`
- Field with path `fines.items[].payer.name` also fillable by `fines.base`
- Field with path `fines.items[].payer.identifier.type` also fillable by `fines.base`
- Field with path `fines.items[].payer.identifier.number` also fillable by `fines.base`
- Field with path `fines.items[].fssp.enforcement_proceeding.number` also fillable by `fines.base`
- Field with path `fines.items[].fssp.enforcement_proceeding.contact` also fillable by `fines.base`

Draft: Add filled_by for fines.base fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `insurance.registry`
- Field with path `accidents.insurance.items[].date.event` also fillable by `insurance.registry`
- Field with path `accidents.insurance.items[].policy.series` also fillable by `insurance.registry`
- Field with path `accidents.insurance.items[].policy.number` also fillable by `insurance.registry`
- Field with path `accidents.insurance.items[].insurer.name` also fillable by `insurance.registry`
- Field with path `accidents.insurance.items[].actuality.date` also fillable by `insurance.registry`
- Field with path `accidents.insurance.date.update` also fillable by `insurance.registry`

Add insurance.registry source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `insurance.vehicle.registry`
- Field with path `accidents.insurance.items[].date.event` also fillable by `insurance.vehicle.registry`
- Field with path `accidents.insurance.items[].policy.series` also fillable by `insurance.vehicle.registry`
- Field with path `accidents.insurance.items[].policy.number` also fillable by `insurance.vehicle.registry`
- Field with path `accidents.insurance.items[].insurer.name` also fillable by `insurance.vehicle.registry`
- Field with path `accidents.insurance.items[].actuality.date` also fillable by `insurance.vehicle.registry`
- Field with path `accidents.insurance.date.update` also fillable by `insurance.vehicle.registry`

Draft: Add insurance.vehicle.registry source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `owner.taxi.history`
- Field with path `additional_info.vehicle.owner.taxi_history.probable_taxi_driver`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.actuality.date`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.items[].vehicle.reg_num`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.items[].vehicle.brand_name_original`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.items[].vehicle.model_name_original`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.items[].full_number`
- Field with path `additional_info.vehicle.owner.taxi_history.taxi_licenses.items[].number` …

Add owner.taxi.history source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `customs.history.items[].owner.tin`
- Field with path `customs.history.items[].country.from.code`
- Field with path `customs.history.items[].country.to.code`
- Field with path `customs.history.items[].sender.name`
- Field with path `customs.history.items[].sender.tin`
- Field with path `customs.history.items[].direction.type`
- Field with path `customs.history.items[].country.original.name`
- Field with path `customs.history.items[].country.original.code`
- Field with path `customs.history.items[].manufacturer.name`
- Field with path `identifiers.vehicle.vin` also fillable by `customs.base`
- Field with path `identifiers.vehicle.body` also fillable by `customs.base`
- Field with path `identifiers.vehicle.chassis` also fillable by `customs.base` …

Add new customs.base fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `fines.items[].location.coordinates` also fillable by `fines.registry`

Draft: Add fines.items[].location.coordinates fillable by fines.registry

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Disabled source with name `references.oats`
- Field with path `additional_info.catalog.oats.*` not fillable by `references.oats` anymore

Disable references.oats source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Field with path `additional_info.vehicle.passport.type`
- Field with path `additional_info.vehicle.passport.status`
- Field with path `additional_info.vehicle.car_scrappage_fees`
- Field with path `additional_info.vehicle.custom_registration`
- Field with path `additional_info.vehicle.restriction.customs`
- Field with path `additional_info.vehicle.restriction.other`
- Field with path `identifiers.vehicle.pts` also fillable by `elpts.online`
- Field with path `identifiers_masked.vehicle.pts` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.passport.number` also fillable by `elpts.online`

Draft: Add elpts.online source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `fines.base.uin`
- Source `fines.base.dln`
- Field with path `fines.items[].date.event` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].date.accident` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].article.code` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].article.description` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].uin` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].description` also fillable by `fines.base.uin` and `fines.base.dln`
- Field with path `fines.items[].vendor.name` also fillable by `fines.base.uin` and `fines.base.dln` …

Draft: Add `fines.base.uin` and `fines.base.dln` sources

---

CHANGELOG.md
__tests__/fields/fields_list.test.ts
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `vin.decoder`
- Field with path `tech_data.brand.id` also fillable by `vin.decoder`
- Field with path `tech_data.brand.name.original` also fillable by `vin.decoder`
- Field with path `tech_data.brand.name.normalized` also fillable by `vin.decoder`
- Field with path `tech_data.model.id` also fillable by `vin.decoder`
- Field with path `tech_data.model.name.original` also fillable by `vin.decoder`
- Field with path `tech_data.model.name.normalized` also fillable by `vin.decoder`
- Field with path `tech_data.year` also fillable by `vin.decoder`
- Field with path `tech_data.engine.fuel.type` also fillable by `vin.decoder`
- Field with path `tech_data.engine.fuel.type_id` also fillable by `vin.decoder`
- Field with path `tech_data.engine.volume` also fillable by `vin.decoder`
- Field …

Add source 'vin.decoder'

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field `accidents.has_accidents` also fillable by:
- `gibdd.dtp`
- `dtp.registry`
- `insurance.dtp`
- `insurance.dtp.basalt`
- `insurance.registry`
- `insurance.vehicle.registry`
- `gibdd.stat.registry`

Change `accidents.has_accidents` fillable by list

---

CHANGELOG.md
__tests__/Makefile
__tests__/sources/sources_list.test.ts
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `fssp.base`
- Disabled source with name `customs.base`
- Disabled source with name `insurance.dtp`
- Disabled source with name `insurance.dtp.basalt`
- Disabled source with name `insurance.registry`
- Disabled source with name `owner.taxi.history`
- Field `additional_info.vehicle.owner.enforcement_proceedings.has_proceedings` not fillable by `fssp.base` anymore
- Field `tech_data.brand.name.original` not fillable by `customs.base` anymore
- Fields `identifiers.*` not fillable by `customs.base` anymore
- Fields `identifiers_masked.*` not fillable by `customs.base` anymore
- Fields `tech_data.*` not fillable by `customs.base` anymore
- Fields `customs.history.*` not fillable by `customs.base` anymore
- Fields `mileages.items[].*` not fillable by `customs.base` anymore
- Fields …

Remove and disable deprecated sources

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Sources:
- `base.alt`
- `base.ext`
- `base.registry`
- `base.registry.retry`
- `fines.madiampp`
- `gibdd.diagnostic.cards`
- `gots.history`
- `ramiosago.base`
- `ramiosago.base.ext`
- `repairs.history`
- `rsaosago.base.ext`
- `rsaosago.base.history`

Remove deprecated sources

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `fines.base.ext`
- Field `fines.has_fines` not fillable by `fines.base.ext` anymore
- Field `fines.date.update` not fillable by `fines.base.ext` anymore
- Fields `fines.items[].*` not fillable by `fines.base.ext` anymore

Remove fines.base.ext source

---

CHANGELOG.md
__tests__/Makefile
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `eaisto.basalt`
- Source `pledge.online`
- Fields `identifiers.*` not fillable by `eaisto.basalt` anymore
- Fields `identifiers_masked.*` not fillable by `eaisto.basalt` anymore
- Fields `diagnostic_cards.*` not fillable by `eaisto.basalt` anymore
- Fields `mileages.*` not fillable by `eaisto.basalt` anymore
- Fields `pledges_online.*` not fillable by `pledge.online` anymore

Draft: Remove pledge and eaisto basalt sources

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `elpts.online`
- Field with path `identifiers.vehicle.pts` also fillable by `elpts.online`
- Field with path `identifiers_masked.vehicle.pts` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.passport.number` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.passport.type` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.passport.status` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.utilization_tax` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.customs_registration` also fillable by `elpts.online`
- Field with path `additional_info.vehicle.restriction.customs` also fillable by `elpts.online` …

Add elpts.online source
