avtocod/specs

fields/default/fields_list.json

Добавил в описание возможные значения `repairs.history.items.repairer.type` и `repairs.history.items.repairer.description`

Changed repairs.history field description

---

CHANGELOG.md
fields/default/examples/empty.json
fields/default/examples/full.json
fields/default/fields_list.json

- Field with path `leasings.items[].lessor.company.name`
- Field with path `leasings.used_in_leasing`

Fields added

---

CHANGELOG.md
README.md
fields/default/examples/empty.json
fields/default/examples/full.json
fields/default/fields_list.json

Это исправление?      | Да
- Field with path `tech_data.brand.logotype.uri`
- Field with path `insurance.osago.items[].date.end`
- Field with path `calculate.osago.price.current.yearly.min`
- Field with path `calculate.osago.price.current.yearly.max`
- Field with path `calculate.osago.price.moscow.yearly.min`
- Field with path `calculate.osago.price.moscow.yearly.max`
- Field with path `calculate.osago.price.moscow_region.yearly.min`
- Field with path `calculate.osago.price.moscow_region.yearly.max`
Исправление #18 
>
> * Добавь заголовок новой версии вида `## v1.x.x`, если его не существует
> * Добавь описания в секции `added`/`changed`/`fixed`
> * Добавь ссылку на …

v2.7.0 - Add new fields

---

.travis.yml
CHANGELOG.md
composer.json
sdk/php/src/Specifications.php
sdk/php/tests/SpecificationsTest.php

- **PHP SDK** method `version` _(returns current package version)_
>
> * Добавь заголовок новой версии вида `## v3.x.x`, если его не существует
> * Добавь описания в секции `Added` / `Changed` / `Fixed`
> * Добавь ссылку на соответствующие issues `[#000]`
> * Добавь ссылки на issues в конец документа

Add version method (#44)

---

CHANGELOG.md
reports/default/examples/full.json
reports/default/json-schema.json

Это исправление?      | Да
Это новый функционал? | Нет
- Vin code in examples changed from `C5KY36SZRBD974789` to `EXAMPL0V1N1000000`

Change example vin value

---

CHANGELOG.md
sdk/php/src/Specifications.php
sdk/php/tests/SpecificationsTest.php

Это исправление?      | Да
Это новый функционал? | Нет
Changelog updated
>
> * Добавь заголовок новой версии вида `## v3.x.x`, если его не существует
> * Добавь описания в секции `Added` / `Changed` / `Fixed`
> * Добавь ссылку на соответствующие issues `[#000]`
> * Добавь ссылки на issues в конец документа

Update changelog and add casting for Specifications::getJsonFileContent()

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

Это исправление?      |  Нет
> Добавлено поле `attributes` в блок `registration_actions.items[]`
Исправление #61 
>
> * Добавь заголовок новой версии вида `## v3.x.x`, если его не существует
> * Добавь описания в секции `Added` / `Changed` / `Fixed`
> * Добавь ссылку на соответствующие issues `[#000]`
> * Добавь ссылки на issues в конец документа

Add field into registrations actions

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `gibdd.fines` [#73]
- Field with path `fines.items[].photos[].type` [#73] 
- Field with path `fines.items[].photos[].uri` [#73]
- Field with path `fines.items[].date.event` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].article.code` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].article.description` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].description` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].vendor.name` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].amount.value` also fillable by `gibdd.fines` [#73]
- Field with path `fines.items[].amount.total` also fillable by …

Add new source gibdd.fines

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `additional_info.vehicle.owner.phone_number` [#75] 
- Field with path `additional_info.vehicle.owner.geo.postal_code` [#75]
Fixes #75

Add new base fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

Added fields 
`additional_info.catalog.transdekra.items[].rsa_code`  #71 
`additional_info.catalog.transdekra.items[].modification_id`  #71 
`additional_info.catalog.transdekra.items[].relevance`  #71

Add fields source transdekra

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Description for field `additional_info.vehicle.owner.phone_number` [#77]
Fixes #77

Change description for phone_number field

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/execute-tests.yml
.travis.yml
CHANGELOG.md
Dockerfile
Makefile
composer.json
docker-compose.yml

- Maximal `illuminate/*` packages version now is `6.*`
- GitHub actions for a tests running

update illuminate up to 6.x

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sdk/php/tests/SpecificationsTest.php

Added new field to mileages
```
{
"path": "mileages.items[].filled_by.source",
"description": "Пробеги: Имя источника, от которого получено значение пробега",
"types": [
"string"
],
"fillable_by": []
}
```
Issue #91

Add field to mileages

---

CHANGELOG.md
reports/default/json-schema.json

Fixed typo of possible value for `service_history.items[].service.type`

Fixed typo of possible value

---

CHANGELOG.md
reports/default/json-schema.json

- Field with path `mileages.items[].filled_by.source` now may have value `customs.base` [#94]
[#94]:https://github.com/avtocod/specs/issues/94
Fixes #94

Added new possible value

---

.github/workflows/execute-tests.yml
CHANGELOG.md
Makefile

[CI] Changelog file linting added

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

Added base as fillable_by for fields where exist base.ext
Closes #121

Add base as fillable by

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Fix description for a field with path `registration_actions.items[].attributes` in `./fields/default/fields_list.json` [#127]
- Fix description for a field with path `registration_actions.items[].usage_allowed` in `./fields/default/fields_list.json` [#127]
- Fix description for a field with path `registration_actions.has_annulment` in `./reports/default/json-schema.json` [#127]
- Fix description for a field with path `ownership.history.items[].last_operation.code` in `./reports/default/json-schema.json` [#127]
- Fix description for a field with path `ownership.history.items[].last_operation.description` in `./reports/default/json-schema.json` [#127]
- Fix description for a field with path …

Fix some fields descriptions

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/full.json
reports/default/json-schema.json

- Example for `repairs` block with `Bodyshop` values for `repairs.history.items[].repairer.type`
Closes # (issue)

Added repairer type bodyshop for repairs

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `images.archive`
- Field with path `images.photos.items[].uri` also fillable by `images.archive` source
- Field with path `images.photos.items[].date.issued` also fillable by `images.archive` source
- Field with path `images.photos.items[].vehicle.model.name` also fillable by `images.archive` source
- Field with path `images.photos.items[].vehicle.brand.name` also fillable by `images.archive` source
- Field with path `ads.history.items[].geo` also fillable by `images.archive` source
- Field with path `ads.history.items[].text` also fillable by `images.archive` source
- Field with path `ads.history.items[].date.publish` also fillable by `images.archive` source …

Add images.archive source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `tech_data.generations[].name`
- Field with path `tech_data.generations[].is_restyling`
- Field with path `tech_data.generations[].years.start`
- Field with path `tech_data.generations[].years.end`
- Field with path `tech_data.generations[].bodies[].type`
- Field with path `tech_data.generations[].bodies[].modifications[].name`
- Field with path `tech_data.generations[].bodies[].modifications[].engine.fuel.type`
- Field with path `tech_data.generations[].bodies[].modifications[].engine.power.hp`
- Field with path `tech_data.generations[].bodies[].modifications[].engine.volume`
- Field with path `tech_data.generations[].bodies[].modifications[].transmission.type` …

Add tech data generations fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/full.json
reports/default/json-schema.json

- Added value `Agency` to `repairs.history.items[].repairer.type` set
- Added value `RETRO CALCULATION` to `repairs.history.items[].task_process` set
- Added another pattern to `pts_code`
Fixes #143

Added repairs enums values. Added new pattern for pts_code

---

CHANGELOG.md
reports/default/json-schema.json

- Fixed typo of possible value for `commercial_use.items[].company.type`

Fixed typo of possible value for 'commercial_use.items[].company.type'

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `references.tecdoc`
- Field with path `additional_info.catalog.tecdoc.items[].manufacturer_id`
- Field with path `additional_info.catalog.tecdoc.items[].model_id`
- Field with path `additional_info.catalog.tecdoc.items[].id`
- Field with path `additional_info.catalog.tecdoc.items[].name`
- Field with path `additional_info.catalog.tecdoc.items[].description`

Added references.tecdoc source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `service.history.fitservice`
- Field with path `service_history.items[].dealer.name` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].dealer.branch.name` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].date.end` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].amount.value` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].service.content` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].service.spare_parts` also fillable by `service.history.fitservice`
- Field with path `service_history.items[].service.recommendations` also fillable by `service.history.fitservice` …

Add service.history.fitservice source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `fines.base.ext`
- Field with path `fines.items[].date.event` also fillable by `fines.base.ext`
- Field with path `fines.items[].article.code` also fillable by `fines.base.ext`
- Field with path `fines.items[].article.description` also fillable by `fines.base.ext`
- Field with path `fines.items[].description` also fillable by `fines.base.ext`
- Field with path `fines.items[].vendor.name` also fillable by `fines.base.ext`
- Field with path `fines.items[].amount.value` also fillable by `fines.base.ext`
- Field with path `fines.items[].amount.total` also fillable by `fines.base.ext`
- Field with path `fines.items[].discount.percent` also fillable by `fines.base.ext`
- Field with path `fines.items[].discount.date.end` also fillable by `fines.base.ext` …

Add fines.base.ext source

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
sources/default/sources_list.json

- Source `base.tech` marked as disabled
- Source `carfax.check` marked as disabled

Disabled base.tech, carfax.check sources

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `gots.history`
- Field with path `gots_auctions.items[].vehicle.mileage`
- Field with path `gots_auctions.items[].vehicle.damage.value`
- Field with path `gots_auctions.items[].vehicle.damage.descriptions`
- Field with path `gots_auctions.items[].auction.date`
- Field with path `gots_auctions.items[].auction.number`
- Field with path `gots_auctions.items[].auction.client.name`
- Field with path `gots_auctions.items[].auction.client.postal_code`
- Field with path `gots_auctions.items[].auction.client.city`
- Field with path `gots_auctions.items[].auction.client.address_line`
- Field with path `gots_auctions.items[].auction.client.phone_number`

Add gots.history source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `pledges.date.update`

Add pledges.date.update field

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json
vehicles/default/models_agricultural.json
vehicles/default/models_artic.json
vehicles/default/models_atv.json
vehicles/default/models_autoloader.json
vehicles/default/models_bulldozer.json
vehicles/default/models_bus.json
vehicles/default/models_construction.json
vehicles/default/models_crane.json
vehicles/default/models_dredge.json
vehicles/default/models_light_truck.json
vehicles/default/models_motorcycle.json
vehicles/default/models_municipal.json
vehicles/default/models_scooter.json
vehicles/default/models_self_loader.json
vehicles/default/models_snowmobile.json
vehicles/default/models_trailer.json
vehicles/default/models_truck.json
vehicles/default/types.json

Update `./vehicles/marks.json` and `./vehicles/models_*.json`

Update marks and models lists

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `identifiers_masked.vehicle.vin`
- Field with path `identifiers_masked.vehicle.reg_num`
- Field with path `identifiers_masked.vehicle.sts`
- Field with path `identifiers_masked.vehicle.pts`
- Field with path `identifiers_masked.vehicle.body`
- Field with path `identifiers_masked.vehicle.chassis`
- Definition `vin_code_masked` in `./reports/default/json-schema.json`
- Definition `grz_code_masked` in `./reports/default/json-schema.json`
- Definition `sts_code_masked` in `./reports/default/json-schema.json`
- Definition `pts_code_masked` in `./reports/default/json-schema.json`
- Definition `body_code_masked` in `./reports/default/json-schema.json`
- Definition `chassis_code_masked` in `./reports/default/json-schema.json`

Add identifiers_masked.vehicle.* fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `identifiers.manufacture.vin`

Add identifiers.manufacture.vin field

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `gibdd.diagnostic.cards`
- Field with path `identifiers.vehicle.vin` also fillable by `gibdd.diagnostic.cards`
- Field with path `identifiers.vehicle.body` also fillable by `gibdd.diagnostic.cards`
- Field with path `identifiers.vehicle.chassis` also fillable by `gibdd.diagnostic.cards`
- Field with path `identifiers_masked.vehicle.vin` also fillable by `gibdd.diagnostic.cards`
- Field with path `identifiers_masked.vehicle.body` also fillable by `gibdd.diagnostic.cards`
- Field with path `identifiers_masked.vehicle.chassis` also fillable by `gibdd.diagnostic.cards`
- Field with path `diagnostic_cards.items[].date.from` also fillable by `gibdd.diagnostic.cards`
- Field with path `diagnostic_cards.items[].date.to` also fillable by `gibdd.diagnostic.cards` …

Add gibdd.diagnostic.cards source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `insurance.osago.items[].vehicle.seats.count`

Add insurance.osago.items[].vehicle.seats.count field

---

CHANGELOG.md
__tests__/vehicles/vehicles.d.ts
__tests__/vehicles/vehicles_marks.test.ts
vehicles/default/marks.json

- Vehicle `logotype_uri` field in `./vehicle/default/marks.json`

Add vehicle marks logos

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `tech_data.generations[].id`
- Field with path `tech_data.generations[].bodies[].id`
- Field with path `tech_data.generations[].bodies[].modifications[].id`

Add tech_data.generations[].*.id fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `service.history.filter`
- Field with path `service_history.date.update` also fillable by `service.history.filter`
- Field with path `service_history.items[].type` also fillable by `service.history.filter`
- Field with path `service_history.items[].dealer.name` also fillable by `service.history.filter`
- Field with path `service_history.items[].date.end` also fillable by `service.history.filter`
- Field with path `service_history.items[].amount.value` also fillable by `service.history.filter`
- Field with path `service_history.items[].amount.currency` also fillable by `service.history.filter`
- Field with path `service_history.items[].service.type` also fillable by `service.history.filter`
- Field with path `service_history.items[].service.content` also fillable by …

Add new source service.history.filter

---

CHANGELOG.md
reports/default/json-schema.json

- Extend enum with `service.history.wilgood` value for field `mileages.items[].filled_by.source` in `./reports/default/json-schema.json`

extend enum

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `base.moscow`, `base.taxi`, `base.tech`, `carfax.check`, `carprice`, `tech.ext`, `tech.base`, `ramiosago.alt`, `ramiosago.alt.ext`, `pledge.fnp`, `references.tecdoc`, `calc.osago`

Remove unused sources

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

removed rsaosago.base.alt

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `rsaosago.base.history`
- Field with path `insurance.osago.*` also fillable by `rsaosago.base.history`

add rsaosago-base-history-source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `tech_data.type.code`
- Field with path `tech_data.wheel.position_code`
- Field with path `additional_info.vehicle.exported`

add fields for alpha

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `accidents.insurance.date.update`

Add accidents.insurance.date.update field

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

Add sources `base.registry`, `base.registry.retry`.
- Source `base.registry`
- Source `base.registry.retry`
- Field with path `identifiers.vehicle.vin` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers.vehicle.body` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers.vehicle.reg_num` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers.vehicle.chassis` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers_masked.vehicle.vin` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers_masked.vehicle.body` also fillable by `base.registry`, `base.registry.retry`
- Field with path `identifiers_masked.vehicle.chassis` also …

Add sources `base.registry`, `base.registry.retry`

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

Add new source osago.registry

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
sources/default/sources_list.json

- Sources `ramiosago.base.ext`, `ramiosago.base`, `rsaosago.base.ext`, `gibdd.diagnostic.cards` marked as disabled

Disable sources

---

CHANGELOG.md
__tests__/sources/sources_list.test.ts
sources/default/sources_list.json

- Source `references.transdekra` marked as disabled

Disable referenses transdekra source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `vehicle.price`
- Field with path `market_prices.appraisal.amount.max`
- Field with path `market_prices.appraisal.amount.min`
- Field with path `market_prices.appraisal.amount.optimal`
- Field with path `market_prices.appraisal.reasons.used_in_taxi`
- Field with path `market_prices.appraisal.reasons.accidents.count`
- Field with path `market_prices.appraisal.reasons.ownerships.count`
- Field with path `market_prices.appraisal.date.update`

Draft: add vehicle.price source

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

- Updated vehicles marks and models specs

Draft: update marks and models specs

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `gibdd.wanted.registry`
- Field with path `stealings.items[].entry`
- Field with path `stealings.items[].vehicle.vin`
- Field with path `stealings.items[].vehicle.body`
- Field with path `stealings.items[].vehicle.year`
- Field with path `stealings.items[].actuality.date`
- Field with path `stealings.items[].vehicle.brand.uid`
- Field with path `stealings.items[].vehicle.model.uid`
- Field with path `sstealings.items[].initiator.region`
- Field with path `stealings.items[].vehicle.brand.name`
- Field with path `stealings.is_wanted` also fillable by `gibdd.wanted.registry`
- Field with path `stealings.date.update` also fillable by `gibdd.wanted.registry`
- Field with path `stealings.items[].date.stealing` also fillable by `gibdd.wanted.registry`

Draft: Add source gibdd.wanted.registry

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `eaisto.registry`
- Field with path `diagnostic_cards.items[].actuality.date`
- Field with path `additional_info.vehicle.techreglament_category.code`
- Field with path `additional_info.vehicle.techreglament_category.description`
- Field with path `identifiers.vehicle.vin` also fillable by `eaisto.registry`
- Field with path `identifiers.vehicle.body` also fillable by `eaisto.registry`
- Field with path `identifiers.vehicle.chassis` also fillable by `eaisto.registry`
- Field with path `identifiers.vehicle.reg_num` also fillable by `eaisto.registry`
- Field with path `identifiers_masked.vehicle.vin` also fillable by `eaisto.registry`
- Field with path `identifiers_masked.vehicle.body` also fillable by `eaisto.registry`
- Field with path `identifiers_masked.vehicle.reg_num` also …

Draft: Add source eaisto registry

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `insurance.dtp.basalt`
- Field with path `accidents.insurance.date.update` also fillable by `insurance.dtp.basalt`
- Field with path `accidents.insurance.items[].date.event` also fillable by `insurance.dtp.basalt`
- Field with path `accidents.insurance.items[].insurer.name` also fillable by `insurance.dtp.basalt`
- Field with path `accidents.insurance.items[].policy.series` also fillable by `insurance.dtp.basalt`
- Field with path `accidents.insurance.items[].policy.number` also fillable by `insurance.dtp.basalt`
- Field with path `accidents.insurance.items[].actuality.date` also fillable by `insurance.dtp.basalt`

Add source insurance.dtp.basalt

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `registration_actions.items[].usage_allowed` also fillable by `base.basalt`

Draft: `base.basalt` fills `registration_actions.items[].usage_allowed` field

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

Add vehicle marks and models

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `insurance.osago.items[].date.cancel`
- Field with path `insurance.osago.items[].policy_replaced.series`
- Field with path `insurance.osago.items[].policy_replaced.number`
- Field with path `insurance.osago.items[].policy_replacement.series`
- Field with path `insurance.osago.items[].policy_replacement.number`

Add insurance osago fields

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `insurance.osago.items[].policy_replaced[].series`
- Field with path `insurance.osago.items[].policy_replaced[].number`
- Field with path `insurance.osago.items[].policy_replaced.series`
- Field with path `insurance.osago.items[].policy_replaced.number`

Draft: Add replaced insurance policies array

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `hl.taxi`
- Field with path `taxi_analytics.probable_use.is_used` fillable by `hl.taxi`

Add source hl.taxi

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

- Changed Vehicle marks and models specs

Change vehicle marks and models specs

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

Vehicle marks and models specs

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `customs.fts`
- Field with path `customs.history.items[].date.event` also fillable by `customs.fts`
- Field with path `customs.history.items[].country.from.name` also fillable by `customs.fts`
- Field with path `customs.history.date.update` also fillable by `customs.fts`
- Field with path `tech_data.brand.name.original` also fillable by `customs.fts`

Add customs.fts source

---

CHANGELOG.md
vehicles/default/models_light_truck.json

- Add ID_MARK_GAZ_MODEL_GAZEL_NN, ID_MARK_GAZ_MODEL_SOBOL_NN

Add ID_MARK_GAZ models NN

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

Add new marks and models

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

- Vehicle models and marks names

Change marks and models names

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

Change vehicle models specs. Add vehicle mark ORA

---

CHANGELOG.md
__tests__/fields/fields_list.test.ts
fields/default/fields_list.json
reports/default/json-schema.json

- Duplicates of source names in `fields_list.json`.
- Tests on preventing duplicates of source names in `fields_list.json`.

Remove duplicates of source names. Add tests

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json

- Field with path `tech_data.year` also fillable by `customs.base`

field `tech_data.year` fillable by `customs.base`

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `repairs.history.registry`
- Field with path `repairs.history.date.update` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].number.calculation` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].date.calculation` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].cost.total` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].cost.parts` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].cost.paint` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].cost.labour` also fillable by `repairs.history.registry`
- Field with path `repairs.history.items[].car.manufacturer` …

Add repairs.history.registry source

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json
vehicles/default/models_artic.json
vehicles/default/models_truck.json

Update vehicle marks and models specs

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/sources_list.json

- Source `carsharing.base`
- Field with path `carsharing.items[].company.tin`
- Field with path `carsharing.items[].company.type`
- Field with path `carsharing.used_in_carsharing`
- Field with path `carsharing.date.update`

Add carsharing.base source

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json
sources/default/json-schema.json
sources/default/sources_list.json

- Source `insurance.event.probability.score`
- Field with path `insurance_scores.accident_probability.value`

Add source insurance.event.probability.score

---

CHANGELOG.md
__tests__/Makefile
reports/default/json-schema.json

- Value `customs.base` in enum `mileages.items[].filled_by.source`

Fix enum `mileages.items[].filled_by.source`

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

Changed vehicle marks and models specs

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json
vehicles/default/models_light_truck.json

Changed vehicle marks and models specs. Added light trucks

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models_artic.json
vehicles/default/models_bulldozer.json
vehicles/default/models_truck.json

Changed vehicle marks and models specs. Update bulldozer, artic, truck

---

CHANGELOG.md
vehicles/default/marks.json
vehicles/default/models.json

- Updarte Vehicle marks and models specs

Update vehicles mark and models specs

---

CHANGELOG.md
fields/default/fields_list.json
reports/default/examples/empty.json
reports/default/examples/full.json
reports/default/json-schema.json

- Field with path `insurance_scores.payout.value`
- Field with path `insurance_scores.pvu_payout_delta.value`
- Field with path `insurance_scores.pvu_accident_probability.value`

Add insurance_scores fields
